language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

services:
  - redis-server

env:
  global:
    - REPO_NAME=cakephp-redis
    - PLUGIN_NAME=Redis
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2

  matrix:
    - DB=mysql CAKE_VERSION=2.6
    - DB=mysql CAKE_VERSION=2.7
    - DB=mysql CAKE_VERSION=2.8
    - DB=mysql CAKE_VERSION=2.9

matrix:
  include:
    - php: 5.6
      env:
        - COVERALLS=1
    - php: 5.6
      env:
        - PHPCS=1
    - php: 5.6
      env:
        - FOC_VALIDATE=1
  exclude:
    - php: 7.0
      env: DB=mysql CAKE_VERSION=2.6
    - php: 7.0
      env: DB=mysql CAKE_VERSION=2.7
    - php: 7.0
      env: DB=mysql CAKE_VERSION=2.8
    - php: 7.1
      env: DB=mysql CAKE_VERSION=2.6
    - php: 7.1
      env: DB=mysql CAKE_VERSION=2.7
    - php: 7.1
      env: DB=mysql CAKE_VERSION=2.8

branches:
  only:
    - master

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - git clone -b master https://github.com/Oefenweb/travis --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
  hipchat:
    rooms:
      secure: BgtN4zIM+HqmIIvGb5aJz3vuu2ACF5k/1iJb32B/BSZE7hQxJ9iSsnY0naZzv81cmFVXmndzp4I4dM8wLrISScqSz3iM7NNVxMSm+FVQt63DckikO39Slyh8HfSyY3pxuIzPuecuIs85Li1z2KnBue34QRyMqmaAYS+sdTXZONM=
