language: php

php:
  - 7.0
  - 7.1
  - 7.2

services:
  - redis-server

env:
  global:
    - REPO_NAME=cakephp-redis
    - PLUGIN_NAME=Redis
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2

    - secure: "NRP8WNBaBZnMrB0fyu19pReMYORhmf9y+LdxHoBCCmJGlm8ELpup0DinezG57kTTpvPRqlUCZF0XahZj5TAsb8FhI4FRUqPpLT1Osolz9UFHq90pe6nECmqkfAC+aU5jrXOG8q0Xd8UuJ4fpKRdS/dfmRY7QUPw3Cmv7B9TNmEI="

  matrix:
    - CAKE_VERSION=2.9
    - CAKE_VERSION=2.10 PHPUNIT_VERSION=^5.7

matrix:
  include:
    - php: 7.1
      env:
        - CODECOVERAGE=1 PHPUNIT_VERSION=^5.7
    - php: 7.1
      env:
        - PHPCS=1
    - php: 7.1
      env:
        - FOC_VALIDATE=1
  exclude:
    - php: 7.2
      env: CAKE_VERSION=2.9

branches:
  only:
    - master

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash

  - git clone -b master https://github.com/Oefenweb/travis --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
  hipchat:
    rooms:
      secure: BgtN4zIM+HqmIIvGb5aJz3vuu2ACF5k/1iJb32B/BSZE7hQxJ9iSsnY0naZzv81cmFVXmndzp4I4dM8wLrISScqSz3iM7NNVxMSm+FVQt63DckikO39Slyh8HfSyY3pxuIzPuecuIs85Li1z2KnBue34QRyMqmaAYS+sdTXZONM=
