language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

services:
  - redis-server

env:
  global:
    - REPO_NAME=cakephp-redis
    - PLUGIN_NAME=Redis
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=master

  matrix:
    - DB=mysql CAKE_VERSION=2.3
    - DB=mysql CAKE_VERSION=2.4
    - DB=mysql CAKE_VERSION=2.5
    - DB=mysql CAKE_VERSION=2.6

matrix:
  include:
    - php: 5.3
      env:
        - COVERALLS=1
    - php: 5.3
      env:
        - PHPCS=1 PHPCS_ARGS="-p --extensions=php --standard=CakePHP --ignore=vendor/ -n ."
    - php: 5.3
      env:
        - FOC_VALIDATE=1

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
  hipchat:
    rooms:
      secure: BgtN4zIM+HqmIIvGb5aJz3vuu2ACF5k/1iJb32B/BSZE7hQxJ9iSsnY0naZzv81cmFVXmndzp4I4dM8wLrISScqSz3iM7NNVxMSm+FVQt63DckikO39Slyh8HfSyY3pxuIzPuecuIs85Li1z2KnBue34QRyMqmaAYS+sdTXZONM=
